"use client"

import Link from "next/link"
import { InternalHero, InternalPage } from "@/components/internal-page"
import { CheckoutButton } from "@/components/store/checkout-button"
import { useCart } from "@/components/store/cart-context"
import { formatCurrency } from "@/lib/store"

export default function CartPage() {
  const { items, subtotalCents, removeFromCart, updateQuantity } = useCart()
  return <InternalPage solid="dodecahedron"><InternalHero eyebrow="Store" title="Your cart">Everything here is selected to support the work you are building.</InternalHero><section className="px-6 py-16"><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[1fr_20rem]">{items.length ? <div className="space-y-4">{items.map((item) => <article key={item.productId} className="flex flex-wrap items-center gap-4 border border-[var(--mercury)] bg-[var(--carbon)]/70 p-5"><div className="flex h-14 w-14 items-center justify-center border border-[var(--mercury)] text-2xl text-[var(--halo)]">☉</div><div className="min-w-44 flex-1"><h2 className="font-[family-name:var(--font-display)] text-xl">{item.name}</h2><p className="mt-1 font-[family-name:var(--font-mono)] text-xs text-[var(--halo)]">{formatCurrency(item.priceCents)}</p></div><div className="flex items-center gap-3"><button onClick={() => updateQuantity(item.productId, item.quantity - 1)} className="h-8 w-8 border border-[var(--mercury)]">−</button><span className="w-4 text-center font-[family-name:var(--font-mono)]">{item.quantity}</span><button onClick={() => updateQuantity(item.productId, item.quantity + 1)} className="h-8 w-8 border border-[var(--mercury)]">+</button></div><button onClick={() => removeFromCart(item.productId)} className="font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[.12em] text-[var(--ghost)] hover:text-red-300">Remove</button></article>)}</div> : <div className="border border-dashed border-[var(--mercury)] p-12 text-center"><p className="font-[family-name:var(--font-mono)] text-sm text-[var(--ghost)]">Your cart is empty.</p><Link href="/store" className="mt-5 inline-block text-xs uppercase tracking-[.14em] text-[var(--halo)]">Browse the store →</Link></div>}<aside className="h-fit border border-[var(--halo)]/30 bg-[var(--carbon)]/85 p-6"><p className="font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[.18em] text-[var(--ghost)]">Order summary</p><div className="mt-5 flex justify-between"><span>Subtotal</span><strong className="font-[family-name:var(--font-display)] text-xl text-[var(--halo)]">{formatCurrency(subtotalCents)}</strong></div><p className="mt-3 text-xs leading-5 text-[var(--ghost)]">Shipping, when applicable, is confirmed in Stripe checkout.</p><CheckoutButton items={items} className="mt-6 w-full bg-[var(--halo)] px-5 py-4 font-[family-name:var(--font-display)] text-lg text-[var(--void)] disabled:cursor-not-allowed disabled:opacity-50">Checkout securely →</CheckoutButton></aside></div></section></InternalPage>
}
