import type { Metadata } from "next"
import Link from "next/link"
import { Calendar, CheckCircle2, Headphones, Mail, Phone, Shield, Users } from "lucide-react"
import { BookingForm } from "@/components/sandabado/booking-form"

export const metadata: Metadata = { title:"Booking — Sandābādo", description:"Professional booking inquiries for Sandābādo. Managed by ODIN Management and represented by Whole Body Records." }

const representation = [
  { icon:Shield, title:"ODIN Management", subtitle:"Artist management & strategic direction", details:["Founded July 2, 2026", "North America", "management@odin.agency"], href:"mailto:management@odin.agency" },
  { icon:Headphones, title:"Whole Body Records", subtitle:"Independent label & distribution", details:["Founder: Jesse Gawlik", "ASCAP affiliated", "records@wholebody.earth"], href:"mailto:records@wholebody.earth" },
  { icon:Users, title:"Publishing", subtitle:"Performance rights & licensing", details:["PRO: ASCAP", "One-stop clearance", "100% artist ownership"] },
]
const performanceOptions = [
  { title:"Festival / Fair", fee:"$5,000 — $15,000", items:["Full band setup (5–7 piece)", "90-minute main set", "Sound engineering included", "Backline rider available", "Merch table included"] },
  { title:"Club / Theater", fee:"$2,500 — $7,500", items:["Full band setup (4–6 piece)", "75–90 minute headline set", "Opening-act coordination", "Green room required", "Meet & greet option"] },
  { title:"Private Event", fee:"$10,000 — $25,000", items:["Acoustic or full band", "Customizable set length", "Corporate, wedding, or brand", "Full AV production", "Domestic travel included"] },
]
const availability = [
  ["Q4 2026 — limited dates", "West Coast tour window", "September 26 — December 31, 2026"],
  ["Q1 2027 — open", "East Coast expansion", "January 1 — March 31, 2027"],
  ["2027 festival season", "Applications now open", "Submit an inquiry for summer lineup consideration"],
]

export default function BookingPage() { return <div className="star-field min-h-screen"><header className="relative overflow-hidden px-6 pb-20 pt-32 text-center"><div className="pointer-events-none absolute inset-0 -z-10 opacity-70"><div className="absolute left-[-12rem] top-10 h-96 w-96 rounded-full bg-[var(--violet)]/25 blur-[120px]"/><div className="absolute bottom-[-12rem] right-[-8rem] h-96 w-96 rounded-full bg-[var(--gold)]/20 blur-[120px]"/></div><p className="text-[10px] uppercase tracking-[.3em] text-[var(--gold)]">Professional booking inquiries</p><h1 className="mt-5 font-[family-name:var(--font-display)] text-5xl tracking-[.04em] sm:text-7xl">BOOK SANDĀBĀDO</h1><p className="mx-auto mt-5 max-w-2xl text-lg text-[var(--cream)]/65">Managed by <strong className="font-medium text-[var(--cream)]">ODIN Management</strong> · Represented by <strong className="font-medium text-[var(--cream)]">Whole Body Records</strong></p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="#booking-form" className="inline-flex min-h-12 items-center justify-center gap-2 bg-[var(--gold)] px-6 text-xs font-semibold uppercase tracking-[.14em] text-[var(--obsidian)] transition hover:bg-[#e4c450]"><Mail size={16}/>Submit booking request</a><a href="mailto:booking@sandabado.com?subject=Technical%20rider%20request" className="inline-flex min-h-12 items-center justify-center gap-2 border border-white/30 px-6 text-xs font-semibold uppercase tracking-[.14em] text-[var(--cream)] transition hover:border-[var(--gold)] hover:text-[var(--gold)]">Request technical rider</a></div></header>
  <section className="border-y border-[var(--violet)]/20 bg-black/20 px-6 py-14"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3">{representation.map(({ icon:Icon,title,subtitle,details,href }) => <article key={title} className="border border-[var(--violet)]/25 bg-[var(--obsidian)]/65 p-6 text-center"><Icon className="mx-auto text-[var(--violet)]" size={38}/><h2 className="mt-4 font-[family-name:var(--font-display)] text-2xl">{title}</h2><p className="mt-2 text-sm text-[var(--cream)]/55">{subtitle}</p><div className="mt-5 space-y-1 text-sm text-[var(--cream)]/55">{details.map((detail) => href && detail.includes("@") ? <a key={detail} href={href} className="block text-[var(--gold)] hover:underline">{detail}</a> : <p key={detail}>{detail}</p>)}</div></article>)}</div></section>
  <Section title="Performance options"><div className="grid gap-5 md:grid-cols-3">{performanceOptions.map((option) => <article key={option.title} className="border border-[var(--violet)]/20 bg-black/20 p-6"><h3 className="font-[family-name:var(--font-display)] text-2xl text-[var(--gold)]">{option.title}</h3><ul className="mt-5 space-y-2 text-sm text-[var(--cream)]/65">{option.items.map((item) => <li key={item}>— {item}</li>)}</ul><div className="mt-6 border border-white/10 bg-black/20 p-4"><p className="text-[10px] uppercase tracking-[.16em] text-[var(--cream)]/45">Fee range</p><p className="mt-1 text-lg text-[var(--cream)]">{option.fee}</p></div></article>)}</div><p className="mt-8 text-center text-sm text-[var(--cream)]/45">Fees vary by date, location, and production requirements. Rates are negotiable based on capacity guarantees and sponsorship opportunities.</p></Section>
  <section className="border-y border-[var(--violet)]/15 bg-black/20 px-6 py-16"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-2"><div><h2 className="font-[family-name:var(--font-display)] text-4xl">WHY BOOK SANDĀBĀDO?</h2><div className="mt-8 space-y-5">{[["Proven draw","Consistent sell-out crowds at independent venues (100–300 capacity)."],["Professional production","Full technical rider, experienced sound engineers, and efficient load-in."],["Marketing partnership","Active social presence, email list, and press support."],["Flexible routing","Available for single dates or multi-city runs across North America."]].map(([title,body]) => <div key={title} className="flex gap-3"><CheckCircle2 className="mt-1 shrink-0 text-[var(--gold)]" size={19}/><div><h3 className="text-[var(--cream)]">{title}</h3><p className="mt-1 text-sm leading-6 text-[var(--cream)]/55">{body}</p></div></div>)}</div></div><blockquote className="flex items-center border border-[var(--violet)]/20 bg-[var(--obsidian)]/75 p-8 text-center"><div><p className="font-[family-name:var(--font-display)] text-2xl italic leading-9 text-[var(--cream)]/80">“Sandābādo brings a raw, spiritual energy that transforms any venue into something sacred. The crowd leaves changed.”</p><cite className="mt-6 block text-xs not-italic uppercase tracking-[.14em] text-[var(--gold)]">Venue Manager, Red Dog Saloon · Pioneertown</cite></div></blockquote></div></section>
  <Section title="Current availability"><div className="mx-auto max-w-3xl space-y-4">{availability.map(([eyebrow,title,detail]) => <article key={title} className="flex flex-col gap-5 border border-[var(--violet)]/20 bg-black/20 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] uppercase tracking-[.18em] text-[var(--gold)]">{eyebrow}</p><h3 className="mt-2 font-[family-name:var(--font-display)] text-2xl">{title}</h3><p className="mt-1 text-sm text-[var(--cream)]/55">{detail}</p></div><a href="#booking-form" className="shrink-0 border border-[var(--gold)]/60 px-4 py-3 text-center text-[10px] uppercase tracking-[.14em] text-[var(--gold)] transition hover:bg-[var(--gold)] hover:text-[var(--obsidian)]">Check availability</a></article>)}</div></Section>
  <section id="booking-form" className="border-y border-[var(--violet)]/20 bg-black/25 px-6 py-16"><div className="mx-auto max-w-4xl"><p className="text-center text-[10px] uppercase tracking-[.24em] text-[var(--gold)]">ODIN Management</p><h2 className="mt-3 text-center font-[family-name:var(--font-display)] text-4xl">SUBMIT BOOKING REQUEST</h2><p className="mx-auto mt-4 max-w-2xl text-center text-sm leading-6 text-[var(--cream)]/55">We respond within 48 business hours. Please allow up to one week for a complete availability and fee proposal.</p><div className="mt-10"><BookingForm/></div></div></section>
  <section className="px-6 py-16"><h2 className="text-center font-[family-name:var(--font-display)] text-4xl">DIRECT CONTACT</h2><div className="mx-auto mt-10 grid max-w-5xl gap-7 text-center sm:grid-cols-2 lg:grid-cols-4"><Direct icon={Mail} label="Booking" value="booking@sandabado.com" href="mailto:booking@sandabado.com"/><Direct icon={Shield} label="Management" value="management@odin.agency" href="mailto:management@odin.agency"/><Direct icon={Headphones} label="Press" value="press@sandabado.com" href="mailto:press@sandabado.com"/><Direct icon={Phone} label="Phone" value="(952) 212-1170" href="tel:+19522121170"/></div><p className="mt-12 text-center text-xs uppercase tracking-[.14em] text-[var(--cream)]/35">ODIN Management · Whole Body Records · ASCAP affiliated</p></section></div> }

function Section({ title, children }: { title:string; children:React.ReactNode }) { return <section className="px-6 py-16"><div className="mx-auto max-w-7xl"><h2 className="mb-10 text-center font-[family-name:var(--font-display)] text-4xl">{title}</h2>{children}</div></section> }
function Direct({ icon:Icon, label, value, href }: { icon:typeof Mail; label:string; value:string; href:string }) { return <div><Icon className="mx-auto text-[var(--violet)]"/><p className="mt-3 text-[10px] uppercase tracking-[.18em] text-[var(--gold)]">{label}</p><a className="mt-2 block text-sm text-[var(--cream)] hover:text-[var(--gold)] hover:underline" href={href}>{value}</a></div> }
