import Link from "next/link"
import { InternalPage, InternalPanel } from "@/components/internal-page"
import { StudioVideoShowcase } from "@/components/studios/video-showcase"

type FilmStatus = "production" | "completed" | "announced"

const films = [
  { title: "The Instrument", type: "Short Film", year: "2026", runtime: "15 min", director: "Jesse Gawlik", description: "A man discovers that his body is the instrument he has been searching for.", icon: "🜂", color: "#C2542D", status: "production" as const },
  { title: "Glory Peak", type: "Documentary Series", year: "2026", runtime: "8 episodes", director: "Lila Chen", description: "Building sacred geometry in rammed earth, from ground to dodecahedron.", icon: "🜄", color: "#2BA8A0", status: "production" as const },
  { title: "Ground", type: "Short Film", year: "2026", runtime: "12 min", director: "Lila Chen", description: "A meditation on what holds. What roots. What remains.", icon: "🜄", color: "#2BA8A0", status: "completed" as const },
  { title: "Twelve", type: "Feature Documentary", year: "2027", runtime: "TBD", director: "TBD", description: "The Dodecanic System. Twelve Houses. Twelve people. One architecture.", icon: "☉", color: "#C9A227", status: "announced" as const },
]

export default function FilmsPage() {
  return <InternalPage solid="icosahedron" color="43,168,160" lighterBackdrop>
    <section className="px-6 py-16 text-center sm:py-20"><Link href="/pillars/studios" className="inline-block font-[family-name:var(--font-mono)] text-xs uppercase tracking-[.12em] text-[var(--ghost)] transition hover:text-[#2BA8A0]">← Back to Studios</Link><span className="mt-8 block text-4xl">🎬</span><p className="mt-4 font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[.3em] text-[var(--halo-dim)]">Whole Body Films</p><h1 className="mt-4 font-[family-name:var(--font-display)] text-5xl text-[var(--bone)]">Films</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[var(--ghost)]">The visual signal: documentary, narrative, and experimental stories that carry the frequency of truth.</p></section>
    <StudioVideoShowcase eyebrow="Whole Body Films Broadcast" liveVideo={{ title: "The Instrument — Edit Bay", detail: "Live cut review from the film unit", label: "Live broadcast", accent: "#C2542D" }} videos={[{ title: "Glory Peak: Field Notes", detail: "Lila Chen · documentary series", label: "Field log" }, { title: "Ground: Director's Cut", detail: "Lila Chen · short film", label: "Preview" }, { title: "Twelve: Early Signal", detail: "Feature documentary · 2027", label: "In development", accent: "#C9A227" }]} />
    <section className="px-6 pb-12"><div className="mx-auto max-w-4xl"><InternalPanel className="border-[var(--mercury)] bg-[var(--steel)]"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-[family-name:var(--font-mono)] text-xs text-[#2BA8A0]">IN THE EDIT BAY</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-xl text-[var(--bone)]">The Instrument</h2><p className="mt-2 text-sm text-[var(--ghost)]">Short film · Jesse Gawlik. Final cut nearing completion. Premiere Summer 2026.</p></div><span className="inline-flex items-center gap-2 font-[family-name:var(--font-mono)] text-xs text-[#00FFC2]"><span className="size-2 animate-pulse bg-[#00FFC2]" />LIVE</span></div></InternalPanel></div></section>
    <section className="px-6 py-12 sm:py-16"><div className="mx-auto max-w-5xl"><p className="mb-8 font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[.22em] text-[var(--halo-dim)]">In Development</p><div className="space-y-8">{films.map((film) => <InternalPanel key={film.title} className="border-[var(--mercury)] bg-[var(--steel)] p-8"><div className="flex flex-col gap-8 md:flex-row"><FilmPoster film={film} /><div className="flex-1"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-[family-name:var(--font-display)] text-3xl text-[var(--bone)]">{film.title}</h2><p className="mt-1 font-[family-name:var(--font-mono)] text-sm text-[var(--ghost)]">{film.director} · {film.year}</p></div><FilmStatusBadge status={film.status} /></div><p className="mt-5 font-[family-name:var(--font-mono)] text-xs text-[var(--halo-dim)]">{film.type} · {film.runtime}</p><p className="mt-3 leading-7 text-[var(--ghost)]">{film.description}</p><p className="mt-5 font-[family-name:var(--font-mono)] text-xs text-[var(--halo-dim)]">Pillar: <span style={{ color: film.color }}>{film.icon} {film.icon === "🜂" ? "Presence" : film.icon === "☉" ? "Guardian" : "Studios"}</span></p><span className="mt-6 inline-block border border-[var(--mercury)] px-4 py-2 font-[family-name:var(--font-mono)] text-xs uppercase tracking-[.1em] text-[var(--halo-dim)]">{film.status === "production" ? "In Production" : film.status === "completed" ? "Release details soon" : "Announced"}</span></div></div></InternalPanel>)}</div></div></section>
    <section className="border-y border-[var(--mercury)] px-6 py-16 sm:py-20"><div className="mx-auto max-w-4xl"><p className="mb-8 text-center font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[.22em] text-[var(--halo-dim)]">The Film Unit</p><p className="mx-auto mb-8 max-w-2xl text-center leading-7 text-[var(--ghost)]">RED Komodo, Ronin, field audio, drone, and portable lighting. The crew goes where the story is. Filmmakers retain 100% copyright, distribution rights, and creative control. We earn on production services, post-production, and placement commissions — never on owning the story.</p><div className="grid grid-cols-2 gap-4 text-center md:grid-cols-4">{[["RED","Komodo Cinema Camera"],["Ronin","3-Axis Gimbal Stabilizer"],["Drone","Aerial Cinematography"],["Field Audio","Professional Sound Capture"]].map(([name, copy]) => <div key={name} className="border border-[var(--mercury)] bg-[var(--carbon)] p-4"><p className="font-[family-name:var(--font-display)] text-xl text-[#2BA8A0]">{name}</p><p className="mt-1 font-[family-name:var(--font-mono)] text-xs text-[var(--ghost)]">{copy}</p></div>)}</div></div></section>
    <section className="px-6 py-12 text-center"><Link href="/pillars/studios" className="font-[family-name:var(--font-mono)] text-xs uppercase tracking-[.12em] text-[var(--ghost)] transition hover:text-[#2BA8A0]">← Back to Studios</Link></section>
  </InternalPage>
}

function FilmPoster({ film }: { film: (typeof films)[number] }) {
  return <div className="relative flex aspect-video w-full shrink-0 items-center justify-center overflow-hidden border border-[var(--mercury)] bg-[radial-gradient(circle_at_center,var(--film-color)_0%,var(--carbon)_70%)] md:w-64" style={{ "--film-color": `${film.color}36` } as React.CSSProperties}><div className="text-center"><span className="font-[family-name:var(--font-display)] text-6xl" style={{ color: film.color }}>{film.icon}</span><p className="mt-3 font-[family-name:var(--font-display)] text-xl text-[var(--bone)]">{film.title}</p></div><span className="absolute bottom-3 left-3 font-[family-name:var(--font-mono)] text-[9px] uppercase tracking-[.14em] text-[var(--bone)]/60">Whole Body Films</span></div>
}

function FilmStatusBadge({ status }: { status: FilmStatus }) {
  const style = status === "completed" ? { backgroundColor: "rgb(0 255 194 / 15%)", color: "#00FFC2", label: "Completed" } : status === "production" ? { backgroundColor: "rgb(176 38 255 / 15%)", color: "#B026FF", label: "In Production" } : { backgroundColor: "rgb(201 162 39 / 15%)", color: "#C9A227", label: "Announced" }
  return <span className="px-3 py-1 font-[family-name:var(--font-mono)] text-xs uppercase tracking-[.08em]" style={{ backgroundColor: style.backgroundColor, color: style.color }}>{style.label}</span>
}
