"use client"

import { CalendarDays, MapPin, Ticket } from "lucide-react"
import { useCart } from "@/components/store/cart-context"
import { formatCurrency } from "@/lib/store"
import { ticketTiers } from "@/lib/sandabado"

export default function TourPage() {
  const { addToCart } = useCart()
  return <div className="star-field min-h-screen px-6 py-16"><section className="mx-auto max-w-5xl"><p className="text-[10px] uppercase tracking-[.28em] text-[var(--gold)]">One night only</p><h1 className="mt-3 font-[family-name:var(--font-display)] text-5xl leading-tight sm:text-7xl">The Whole Body Gathering</h1><div className="mt-8 grid gap-8 border-y border-[var(--gold)]/25 py-8 sm:grid-cols-2"><div className="space-y-5 text-[var(--cream)]/75"><p className="flex gap-3"><CalendarDays className="shrink-0 text-[var(--gold)]" size={20}/><span><strong className="block text-[var(--cream)]">Saturday, September 26, 2026</strong>Doors 6:00 PM · Show 7:00 PM · Midnight Close</span></p><p className="flex gap-3"><MapPin className="shrink-0 text-[var(--gold)]" size={20}/><span><strong className="block text-[var(--cream)]">Red Dog Saloon</strong>Pioneertown, California</span></p><p className="flex gap-3"><Ticket className="shrink-0 text-[var(--gold)]" size={20}/><span><strong className="block text-[var(--cream)]">100 guests maximum</strong>Reservations are intentionally limited.</span></p></div><div className="border-l-0 border-[var(--violet)]/50 pl-0 sm:border-l sm:pl-8"><p className="text-[10px] uppercase tracking-[.2em] text-[var(--gold)]">Lineup</p><p className="mt-4 font-[family-name:var(--font-display)] text-2xl">Father Atlas</p><p className="mt-1 font-[family-name:var(--font-display)] text-2xl">Palo Xanto</p><p className="mt-5 text-sm text-[var(--cream)]/65">Headliner</p><p className="font-[family-name:var(--font-display)] text-3xl text-[var(--gold)]">Sandābādo</p><p className="text-sm text-[var(--cream)]/65">Full ∞ LOVE album live</p></div></div></section><section className="mx-auto mt-14 max-w-5xl"><p className="text-center text-[10px] uppercase tracking-[.24em] text-[var(--gold)]">Choose your passage</p><div className="mt-7 grid gap-5 md:grid-cols-3">{ticketTiers.map((tier) => <article key={tier.id} className="flex flex-col border border-white/15 bg-white/[.025] p-6"><h2 className="font-[family-name:var(--font-display)] text-3xl">{tier.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-[var(--cream)]/65">{tier.detail}</p><p className="mt-6 font-[family-name:var(--font-display)] text-3xl text-[var(--gold)]">{formatCurrency(tier.priceCents)}</p><button onClick={() => addToCart({ productId:tier.id, name:tier.name, priceCents:tier.priceCents, quantity:1 })} className="mt-7 border border-[var(--gold)] px-4 py-3 text-xs uppercase tracking-[.13em] text-[var(--gold)] transition hover:bg-[var(--gold)] hover:text-[var(--obsidian)]">Get tickets now</button></article>)}</div></section></div>
}
