import Image from "next/image"
import Link from "next/link"
import { ArrowDown, Play } from "lucide-react"
import { EmailCapture } from "@/components/sandabado/email-capture"

export default function HomePage() {
  return <div className="star-field overflow-hidden"><section className="relative isolate flex min-h-[calc(100svh-4rem)] items-center justify-center px-6 py-20 text-center"><Image src="/images/sandabado-album.jpg" alt="∞ LOVE album artwork" fill priority sizes="100vw" className="-z-20 object-cover object-center opacity-60"/><div className="hero-vignette absolute inset-0 -z-10"/><div className="relative max-w-3xl"><p className="text-[10px] uppercase tracking-[.32em] text-[var(--gold)] sm:text-xs">Whole Body Records presents</p><h1 className="mt-6 font-[family-name:var(--font-display)] text-6xl leading-none tracking-[.1em] sm:text-8xl md:text-9xl">SANDĀBĀDO</h1><div className="gold-rule mx-auto mt-7 w-36"/><p className="mt-7 font-[family-name:var(--font-display)] text-3xl italic text-[var(--gold)] sm:text-4xl">∞ LOVE</p><p className="mt-3 text-sm uppercase tracking-[.18em] text-[var(--cream)]/75 sm:text-base">Coming September 26, 2026</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="#inner-circle" className="bg-[var(--gold)] px-5 py-3 text-xs font-semibold uppercase tracking-[.13em] text-[var(--obsidian)]">Pre-save on Apple Music</a><Link href="/tour" className="border border-[var(--cream)]/50 px-5 py-3 text-xs font-semibold uppercase tracking-[.13em] text-[var(--cream)] transition hover:border-[var(--gold)] hover:text-[var(--gold)]">Reserve tickets — Sept 26</Link></div></div><a href="#inner-circle" aria-label="Scroll to Inner Circle signup" className="absolute bottom-7 left-1/2 -translate-x-1/2 text-[var(--gold)]"><ArrowDown size={22}/></a></section>
    <section id="inner-circle" className="border-y border-[var(--gold)]/20 bg-[#0c0b13] px-6 py-16 text-center"><p className="text-[10px] uppercase tracking-[.28em] text-[var(--gold)]">Enter the circle</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-4xl sm:text-5xl">Join the Inner Circle</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-[var(--cream)]/65">Release notes, first listening access, and a direct path to the gathering in Pioneertown.</p><EmailCapture /></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-6 py-20 md:grid-cols-[.8fr_1.2fr] md:items-center"><div className="relative mx-auto aspect-square w-full max-w-md overflow-hidden border border-[var(--gold)]/25"><Image src="/images/sandabado-album.jpg" alt="∞ LOVE cover art" fill sizes="(max-width: 768px) 90vw, 40vw" className="object-cover"/></div><div><p className="text-[10px] uppercase tracking-[.25em] text-[var(--gold)]">Featured transmission</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-4xl sm:text-5xl">ROLLIN&apos; STONE</h2><p className="mt-4 max-w-xl text-base leading-7 text-[var(--cream)]/70">A dust-streaked soul blues opening from ∞ LOVE. 528Hz tuned and made to move under open sky.</p><Link href="/music" className="mt-7 inline-flex items-center gap-2 border border-[var(--violet)] px-5 py-3 text-xs uppercase tracking-[.14em] text-[var(--cream)] transition hover:bg-[var(--violet)]"><Play size={14} fill="currentColor"/> Hear the preview</Link></div></section>
  </div>
}
