import Image from "next/image"
import Link from "next/link"
import { ArrowDown, Play } from "lucide-react"
import { EmailCapture } from "@/components/sandabado/email-capture"
import { CinematicHeroBackground } from "@/components/sandabado/cinematic-hero-background"

export default function HomePage() {
  const heroVideo = process.env.NEXT_PUBLIC_HERO_VIDEO_URL

  return <div className="star-field overflow-hidden"><section className="hero-stage relative isolate flex min-h-[calc(100svh-4rem)] items-end justify-center overflow-hidden px-6 pb-24 pt-20 text-center sm:pb-20"><CinematicHeroBackground videoSrc={heroVideo}/><div className="hero-copy relative z-10 max-w-4xl"><p className="hero-kicker text-[10px] uppercase tracking-[.32em] text-[var(--gold)] sm:text-xs">Whole Body Records presents</p><h1 className="hero-title mt-4 font-[family-name:var(--font-display)] text-6xl leading-none tracking-[.08em] sm:text-8xl md:text-9xl">SANDĀBĀDO</h1><div className="gold-rule mx-auto mt-5 w-36"/><div className="mt-5 flex flex-wrap items-center justify-center gap-x-5 gap-y-1"><p className="font-[family-name:var(--font-display)] text-2xl italic text-[var(--gold)] sm:text-3xl">∞ LOVE</p><p className="text-[10px] uppercase tracking-[.2em] text-[var(--cream)]/80 sm:text-xs">Coming September 26, 2026</p></div><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><a href="#inner-circle" className="hero-primary-action bg-[var(--gold)] px-5 py-3 text-xs font-semibold uppercase tracking-[.13em] text-[var(--obsidian)]">Pre-save on Apple Music</a><Link href="/tour" className="hero-secondary-action border border-[var(--cream)]/60 bg-black/15 px-5 py-3 text-xs font-semibold uppercase tracking-[.13em] text-[var(--cream)] backdrop-blur-sm transition hover:border-[var(--gold)] hover:text-[var(--gold)]">Reserve tickets — Sept 26</Link></div></div><a href="#inner-circle" aria-label="Scroll to Inner Circle signup" className="hero-scroll absolute bottom-6 left-1/2 z-10 -translate-x-1/2 text-[var(--gold)]"><ArrowDown size={22}/></a></section>
    <section id="inner-circle" className="border-y border-[var(--gold)]/20 bg-[#0c0b13] px-6 py-16 text-center"><p className="text-[10px] uppercase tracking-[.28em] text-[var(--gold)]">Enter the circle</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-4xl sm:text-5xl">Join the Inner Circle</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-[var(--cream)]/65">Release notes, first listening access, and a direct path to the gathering in Pioneertown.</p><EmailCapture /></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-6 py-20 md:grid-cols-[.8fr_1.2fr] md:items-center"><div className="relative mx-auto aspect-square w-full max-w-md overflow-hidden border border-[var(--gold)]/25"><Image src="/images/sandabado-album.jpg" alt="∞ LOVE cover art" fill sizes="(max-width: 768px) 90vw, 40vw" className="object-cover"/></div><div><p className="text-[10px] uppercase tracking-[.25em] text-[var(--gold)]">Featured transmission</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-4xl sm:text-5xl">ROLLIN&apos; STONE</h2><p className="mt-4 max-w-xl text-base leading-7 text-[var(--cream)]/70">A dust-streaked soul blues opening from ∞ LOVE. 528Hz tuned and made to move under open sky.</p><Link href="/music" className="mt-7 inline-flex items-center gap-2 border border-[var(--violet)] px-5 py-3 text-xs uppercase tracking-[.14em] text-[var(--cream)] transition hover:bg-[var(--violet)]"><Play size={14} fill="currentColor"/> Hear the preview</Link></div></section>
  </div>
}
