import Link from "next/link"
import type { ReactNode } from "react"
import { HomePlatonicBackground } from "@/components/home-platonic-background"
import { PillarSolid } from "@/components/pillar-solid"
import { PILLARS } from "@/lib/constants"

const sectionShell = "relative flex min-h-[calc(100svh-7rem)] items-center overflow-hidden px-6 py-20 sm:py-24"

const visualPillars = [
  { id:"presence", solid:"Tetrahedron", description:"Embodiment, voice, and the physical practice of arriving.", tone:"#C2542D" },
  { id:"press", solid:"Octahedron", description:"Publishing, communication, and a signal that carries.", tone:"#D4AF37" },
  { id:"studios", solid:"Icosahedron", description:"Creative flow, emotional intelligence, and relational art.", tone:"#2BA8A0" },
  { id:"foundation", solid:"Cube", description:"Structure, systems, ritual, and the architecture of legacy.", tone:"#4A6741" },
  { id:"guardian", solid:"Dodecahedron", description:"The central axis: synthesis, facilitation, and holding space.", tone:"#6D4AFF" },
] as const

export default function HomePage() {
  return <><HomePlatonicBackground /><div className="relative z-10 isolate"><div className="home-gradient-flow pointer-events-none absolute inset-0 -z-10"/>
    <section id="hero" className={sectionShell}>
      <div className="relative mx-auto max-w-6xl text-center [text-shadow:0_2px_28px_rgba(0,0,0,.96)]">
        <p className="font-[family-name:var(--font-mono)] text-[10px] tracking-[.32em] uppercase text-[var(--halo)] sm:text-xs">The Whole Body Constellation</p>
        <h1 className="mx-auto mt-5 max-w-4xl font-[family-name:var(--font-display)] text-5xl leading-[.94] font-semibold text-[var(--bone)] sm:text-6xl lg:text-7xl">Five Pillars. One Whole Body.</h1>
        <div className="mx-auto mt-6 max-w-3xl space-y-4 text-base leading-7 text-[var(--bone)]/78 sm:text-lg"><p>Your birth chart reveals your design. Wholebody.earth maps you to one of five pillars — Presence, Press, Studios, Foundation, Guardian — then guides you to the practice, community, and work that fits your architecture.</p><p className="text-[var(--bone)]/72">A network for sovereign creators.</p></div>
        <Link href="/reading" className="mt-8 inline-block bg-[#FF6FAE] px-6 py-3 font-[family-name:var(--font-mono)] text-xs tracking-[.14em] uppercase text-[var(--void)] shadow-[0_0_24px_rgba(255,111,174,.38)] transition hover:bg-[#FDA4D4]">Get Your Reading →</Link>
        <div className="mt-10 grid gap-5 text-left sm:grid-cols-2 lg:grid-cols-5">{visualPillars.map((item) => { const pillar = PILLARS.find((candidate) => candidate.id === item.id)!; return <Link href={`/pillars/${item.id}`} className="pillar-card group min-h-72 border border-transparent bg-[var(--carbon)]/90 p-5 shadow-[0_16px_38px_rgba(0,0,0,.32)] backdrop-blur-md transition duration-300 hover:-translate-y-2 hover:bg-[var(--steel)]/95" style={{ "--pillar":item.tone, boxShadow:`0 16px 38px rgba(0,0,0,.32), 0 0 24px ${item.tone}20` } as React.CSSProperties} key={item.id}><PillarSolid solid={item.solid}/><p className="mt-5 font-[family-name:var(--font-mono)] text-[10px] tracking-[.16em] uppercase" style={{ color:item.tone }}>{pillar.symbol} {pillar.body} body</p><p className="mt-1 font-[family-name:var(--font-mono)] text-[9px] tracking-[.12em] uppercase text-[var(--ghost)]">{pillar.element} · {pillar.solid}</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-2xl text-[var(--bone)] transition group-hover:text-[var(--pillar)]">{pillar.name}</h2><p className="mt-3 text-sm leading-6 text-[var(--bone)]/72">{item.description}</p><span className="mt-5 block font-[family-name:var(--font-mono)] text-[10px] tracking-[.12em] uppercase" style={{ color:item.tone }}>Explore {pillar.name} →</span></Link> })}</div>
        <Link href="#quincunx" aria-label="Scroll to explore the Quincunx" className="hero-scroll-cue mx-auto mt-10 flex w-fit flex-col items-center gap-2 text-[var(--halo)]"><span className="font-[family-name:var(--font-mono)] text-[10px] tracking-[.24em] uppercase">Follow the constellation</span><span className="hero-scroll-cue-arrow flex h-10 w-6 items-center justify-center border border-[var(--halo)]/55 text-xl">↓</span></Link>
      </div>
    </section>
    <section id="quincunx" className={sectionShell}><div className="relative mx-auto max-w-3xl text-center [text-shadow:0_2px_20px_rgba(0,0,0,.9)]"><div className="mx-auto h-px w-16 bg-[var(--halo)]/35"/><p className="mt-8 font-[family-name:var(--font-mono)] text-[10px] tracking-[.28em] uppercase text-[var(--halo)]">The Quincunx</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-4xl text-[var(--halo)] sm:text-5xl">You are made of the elements.</h2><div className="mt-6 space-y-5 text-lg leading-8 text-[var(--bone)]/80"><p>Physical, mental, emotional, and spiritual bodies move around an etheral center. Your chart shows their relative weight—and the center illuminates when your system holds in balance.</p><p>Whole Body turns that pattern into a real practice: embodiment, signal, creative flow, structure, or synthesis.</p></div><Link href="/reading" className="mt-9 inline-block bg-[#FF6FAE] px-6 py-3 font-[family-name:var(--font-mono)] text-xs tracking-[.14em] uppercase text-[var(--void)] shadow-[0_0_24px_rgba(255,111,174,.38)] transition hover:bg-[#FDA4D4]">Get your Whole Body Reading →</Link></div></section>
    <PillarSection id="presence" pillar="presence" tone="#C2542D" tagline="The shape of ignition." body={["Presence is the physical pillar: breath, movement, voice, boundaries, and the grounded intelligence of the body.", "Start with what is here. Feel your feet. Let the body lead."]}><Feature label="The embodied voice" title="Somatic practice for the signal you carry." text="Breath, grounding, vocal activation, and a return to the physical vessel." tone="#C2542D" /></PillarSection>
    <PillarSection id="press" pillar="press" tone="#D4AF37" tagline="The shape that carries." body={["Press is the mental pillar: writing, speaking, publishing, and shaping a signal that travels without losing its source.", "Your mind does not need more noise. It needs a clear channel."]}><Feature label="Signal architecture" title="A practice for your message." text="Clarify the idea, edit the noise, and make the work easy to find." tone="#D4AF37" /></PillarSection>
    <PillarSection id="studios" pillar="studios" tone="#2BA8A0" tagline="The shape that remembers." body={["Studios is the emotional pillar: art, feeling, relationship, and the creative current that makes a life feel alive.", "Make room for the feeling. Then make something with it."]}><Feature label="Emotional cartography" title="Creative work that lets feeling move." text="Colour mapping, relational practice, free creation, and a path into flow." tone="#2BA8A0" /></PillarSection>
    <PillarSection id="foundation" pillar="foundation" tone="#4A6741" tagline="The shape that endures." body={["Foundation is the spiritual pillar: systems, ritual, roots, and the durable structures that allow meaningful work to remain.", "Without a container, even a true vision spills away."]}><Feature label="The root practice" title="Structure that can hold your work." text="Build rituals, map your systems, and create the conditions for a lasting legacy." tone="#4A6741" /></PillarSection>
    <PillarSection id="guardian" pillar="guardian" tone="#6D4AFF" tagline="The shape that holds." body={["Guardian is the etheral center. It appears when your four outer bodies are in uncommon balance and you are called to hold a whole pattern.", "The center does not dominate. It makes coherence possible."]}><Feature label="The Guardian’s circle" title="Integration for those who hold the whole." text="Facilitation, pattern recognition, integration, and practices for a centered presence." tone="#6D4AFF" /></PillarSection>
    <section className={`${sectionShell} min-h-[70svh]`}><div className="relative mx-auto max-w-3xl text-center [text-shadow:0_2px_24px_rgba(0,0,0,.96)]"><div className="mx-auto h-px w-16 bg-[var(--halo)]/35"/><p className="mt-8 font-[family-name:var(--font-mono)] text-[10px] tracking-[.3em] uppercase text-[var(--halo)]">Your design is waiting</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-4xl text-[var(--halo)] sm:text-5xl">Find the pillar that is asking for you.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[var(--bone)]/85">Enter your birth data. See your weighted Quincunx. Begin with a practice that meets you where you are.</p><Link href="/reading" className="mt-9 inline-block bg-[#FF6FAE] px-7 py-4 font-[family-name:var(--font-display)] text-lg text-[var(--void)] shadow-[0_0_28px_rgba(255,111,174,.42)] transition hover:bg-[#FDA4D4]">Begin your reading →</Link></div></section>
  </div></>
}

function PillarSection({ id, pillar: pillarId, tone, tagline, body, children }: { id:string; pillar:"presence"|"press"|"studios"|"foundation"|"guardian"; tone:string; tagline:string; body:string[]; children:ReactNode }) { const pillar = PILLARS.find((item) => item.id === pillarId)!; return <section id={id} className={sectionShell}><div className="relative mx-auto grid w-full max-w-6xl items-center gap-10 lg:grid-cols-[.95fr_1.05fr]"><div className="[text-shadow:0_2px_18px_rgba(0,0,0,.88)]"><p className="font-[family-name:var(--font-mono)] text-[10px] tracking-[.24em] uppercase" style={{ color:tone }}>{pillar.symbol} {pillar.element} · {pillar.solid}</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-5xl font-semibold" style={{ color:tone }}>{pillar.name}</h2><p className="mt-2 font-[family-name:var(--font-display)] text-2xl italic" style={{ color:tone }}>{tagline}</p><div className="mt-6 space-y-5 text-lg leading-8 text-[var(--bone)]/80">{body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><Link href={`/pillars/${pillar.id}`} className="mt-8 inline-block border px-5 py-3 font-[family-name:var(--font-mono)] text-xs tracking-[.12em] uppercase transition hover:bg-white/5" style={{ color:tone, borderColor:tone }}>{`Explore ${pillar.name} →`}</Link></div><div>{children}</div></div></section> }
function Feature({ label, title, text, tone }: { label:string; title:string; text:string; tone:string }) { return <article className="border bg-[var(--void)]/82 p-6 backdrop-blur-sm" style={{ borderColor:`${tone}66` }}><p className="font-[family-name:var(--font-mono)] text-[10px] tracking-[.18em] uppercase" style={{ color:tone }}>{label}</p><h3 className="mt-4 font-[family-name:var(--font-display)] text-3xl text-[var(--bone)]">{title}</h3><p className="mt-4 text-sm leading-7 text-[var(--bone)]/70">{text}</p><Link href="/events" className="mt-7 inline-block font-[family-name:var(--font-mono)] text-xs tracking-[.1em] uppercase" style={{ color:tone }}>See gatherings →</Link></article> }
