"use client"

import { useState } from "react"

export function LoginForm() {
  const [mode, setMode] = useState<"login" | "register">("login"); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false)
  async function submit(form: HTMLFormElement) { setLoading(true); setMessage(null); const data = new FormData(form); try { const response = await fetch("/api/auth", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ action:mode, email:data.get("email"), password:data.get("password"), name:data.get("name") }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Authentication failed."); if (payload.access_token) { localStorage.setItem("wb-access-token", payload.access_token); location.assign("/account") } else setMessage("Check your email to confirm your account, then sign in.") } catch (error) { setMessage(error instanceof Error ? error.message : "Authentication failed.") } finally { setLoading(false) } }
  return <form onSubmit={(event) => { event.preventDefault(); submit(event.currentTarget) }} className="hud-frame space-y-5 border border-[var(--mercury)] bg-[var(--steel)] p-6"><div className="flex gap-2"><button type="button" onClick={() => setMode("login")} className={`flex-1 border px-3 py-2 font-[family-name:var(--font-mono)] text-xs uppercase ${mode === "login" ? "border-[var(--halo)] text-[var(--halo)]" : "border-[var(--mercury)] text-[var(--ghost)]"}`}>Sign in</button><button type="button" onClick={() => setMode("register")} className={`flex-1 border px-3 py-2 font-[family-name:var(--font-mono)] text-xs uppercase ${mode === "register" ? "border-[var(--halo)] text-[var(--halo)]" : "border-[var(--mercury)] text-[var(--ghost)]"}`}>Register</button></div>{mode === "register" ? <input name="name" required placeholder="Your name" className="w-full border border-[var(--mercury)] bg-[var(--carbon)] px-3 py-3 outline-none focus:border-[var(--halo)]" /> : null}<input name="email" type="email" required placeholder="Email address" className="w-full border border-[var(--mercury)] bg-[var(--carbon)] px-3 py-3 outline-none focus:border-[var(--halo)]"/><input name="password" type="password" required minLength={8} placeholder="Password" className="w-full border border-[var(--mercury)] bg-[var(--carbon)] px-3 py-3 outline-none focus:border-[var(--halo)]"/><button disabled={loading} className="w-full bg-[var(--halo)] px-4 py-3 font-[family-name:var(--font-display)] text-[var(--void)] disabled:opacity-60">{loading ? "Working…" : mode === "login" ? "Enter member area" : "Create account"}</button>{message ? <p className="text-center text-sm text-[var(--ghost)]">{message}</p> : null}</form>
}
