"use client"

import Image from "next/image"
import { ChevronDown, Play } from "lucide-react"
import { useState } from "react"
import { ProductCard } from "@/components/sandabado/product-card"
import { useAudioPlayer } from "@/components/sandabado/audio-player"
import { products, tracks } from "@/lib/sandabado"

export default function MusicPage() {
  const { current, playing, play, toggle } = useAudioPlayer(); const [open, setOpen] = useState<number | null>(null)
  return <div className="star-field"><section className="mx-auto grid max-w-6xl gap-10 px-6 py-16 md:grid-cols-[.8fr_1.2fr] md:items-center"><div className="relative mx-auto aspect-square w-full max-w-md overflow-hidden border border-[var(--gold)]/30"><Image src="/images/releases/sandabado-infinity-love.png" alt="∞ LOVE album cover" fill priority sizes="(max-width:768px) 90vw, 40vw" className="object-cover"/></div><div><p className="text-[10px] uppercase tracking-[.28em] text-[var(--gold)]">The debut record</p><h1 className="mt-3 font-[family-name:var(--font-display)] text-6xl sm:text-7xl">∞ LOVE</h1><div className="gold-rule mt-6 w-32"/><p className="mt-6 text-sm uppercase tracking-[.14em] text-[var(--cream)]/70">13 Tracks · 52 Minutes · 528Hz Tuned</p><p className="mt-5 max-w-xl leading-7 text-[var(--cream)]/65">Soul blues, desert rock, and a ritual for staying open in the great mystery.</p></div></section>
    <section className="mx-auto max-w-4xl px-6 pb-20"><div className="mb-4 flex items-center justify-between"><h2 className="font-[family-name:var(--font-display)] text-3xl">Tracklist</h2><span className="text-[10px] uppercase tracking-[.15em] text-[var(--cream)]/45">30-second previews</span></div><div className="border-y border-white/15">{tracks.map((track) => <article key={track.number} className="border-b border-white/10 last:border-0"><div className="flex items-center gap-3 py-4"><span className="w-7 text-xs text-[var(--gold)]">{String(track.number).padStart(2,"0")}</span><button onClick={() => current?.number === track.number ? toggle() : play(track)} aria-label={`Play preview of ${track.title}`} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-[var(--gold)]/60 text-[var(--gold)] hover:bg-[var(--gold)] hover:text-[var(--obsidian)]"><Play size={13} fill={current?.number === track.number && playing ? "currentColor" : "none"}/></button><div className="min-w-0 flex-1"><h3 className="truncate font-[family-name:var(--font-display)] text-lg">{track.title}</h3><p className="text-xs text-[var(--cream)]/50">{track.style}</p></div><span className="hidden text-xs text-[var(--cream)]/55 sm:block">{track.duration}</span><a href="https://bandcamp.com" target="_blank" rel="noreferrer" className="hidden text-[10px] uppercase tracking-[.11em] text-[var(--gold)] sm:block">Bandcamp</a><button onClick={() => setOpen(open === track.number ? null : track.number)} aria-expanded={open === track.number} className="flex h-8 w-8 items-center justify-center text-[var(--cream)]/65" aria-label={`Show lyrics for ${track.title}`}><ChevronDown className={open === track.number ? "rotate-180 transition" : "transition"} size={17}/></button></div>{open === track.number ? <div className="pb-5 pl-[4.75rem] pr-4"><p className="max-w-xl border-l border-[var(--violet)] pl-4 font-[family-name:var(--font-display)] text-lg italic leading-7 text-[var(--cream)]/75">“{track.lyric}”</p></div> : null}</article>)}</div></section>
    <section className="border-y border-[var(--gold)]/20 bg-[#0d0c14] px-6 py-16"><div className="mx-auto max-w-5xl"><p className="text-[10px] uppercase tracking-[.24em] text-[var(--gold)]">Available now</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-4xl">Carry ∞ LOVE with you.</h2><div className="mt-8 grid gap-5 sm:grid-cols-3">{products.slice(0,3).map((product) => <ProductCard key={product.id} product={product}/>)}</div></div></section>
    <section className="mx-auto max-w-5xl px-6 py-16"><p className="text-[10px] uppercase tracking-[.24em] text-[var(--gold)]">Credits & Metadata</p><div className="mt-5 grid gap-7 border-t border-white/15 pt-6 text-sm leading-6 text-[var(--cream)]/65 sm:grid-cols-2"><div><p><span className="text-[var(--cream)]">Artist:</span> Sandābādo</p><p className="mt-2"><span className="text-[var(--cream)]">Composers:</span> Jesse Gawlik (33.34%), Josh Tomaszewski (33.33%), Christopher Kyser (33.33%)</p><p className="mt-2"><span className="text-[var(--cream)]">Label:</span> Whole Body Records (ASCAP)</p></div><div><p><span className="text-[var(--cream)]">Genre:</span> Soul Blues / Desert Rock</p><p className="mt-2"><span className="text-[var(--cream)]">Keywords:</span> gritty vocals, primal, emotional, driving, anthemic</p><p className="mt-2">No AI used</p><p className="mt-4 text-[var(--gold)]">records@wholebody.earth · (952) 212-1170</p></div></div></section>
  </div>
}
