"use client"

import Link from "next/link"
import { ShoppingBag, X } from "lucide-react"
import { useState } from "react"
import { formatCurrency } from "@/lib/store"
import { CheckoutButton } from "./checkout-button"
import { useCart } from "./cart-context"

export function CartModal() {
  const { items, itemCount, subtotalCents, removeFromCart, updateQuantity, clearCart } = useCart()
  const [open, setOpen] = useState(false)
  return <>
    <button onClick={() => setOpen(true)} className="relative flex items-center gap-2 font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[.12em] text-[var(--ghost)] transition hover:text-[var(--halo)]" aria-label="Open cart"><ShoppingBag size={16}/><span className="hidden lg:inline">Cart</span>{itemCount ? <span className="absolute -right-3 -top-3 flex h-4 min-w-4 items-center justify-center rounded-full bg-[var(--halo)] px-1 text-[9px] text-[var(--void)]">{itemCount}</span> : null}</button>
    {open ? <><button className="fixed inset-0 z-[60] cursor-default bg-black/70" onClick={() => setOpen(false)} aria-label="Close cart overlay"/><aside className="fixed inset-y-0 right-0 z-[70] flex w-full max-w-md flex-col border-l border-[var(--mercury)] bg-[var(--carbon)] shadow-2xl"><header className="flex items-center justify-between border-b border-[var(--mercury)] px-6 py-5"><div><p className="font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[.18em] text-[var(--halo)]">Your selection</p><h2 className="mt-1 font-[family-name:var(--font-display)] text-2xl">Cart</h2></div><button onClick={() => setOpen(false)} className="text-[var(--ghost)] transition hover:text-[var(--bone)]" aria-label="Close cart"><X size={20}/></button></header>
      <div className="flex-1 overflow-y-auto p-6">{items.length ? <div className="space-y-5">{items.map((item) => <article key={item.productId} className="border-b border-[var(--mercury)] pb-5"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center border border-[var(--mercury)] text-[var(--halo)]">{item.pillar ? "◈" : "☉"}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><h3 className="font-[family-name:var(--font-display)] text-lg">{item.name}</h3><span className="font-[family-name:var(--font-mono)] text-xs text-[var(--halo)]">{formatCurrency(item.priceCents)}</span></div><div className="mt-3 flex items-center gap-3"><button onClick={() => updateQuantity(item.productId, item.quantity - 1)} className="h-7 w-7 border border-[var(--mercury)] text-[var(--ghost)]">−</button><span className="w-4 text-center font-[family-name:var(--font-mono)] text-sm">{item.quantity}</span><button onClick={() => updateQuantity(item.productId, item.quantity + 1)} className="h-7 w-7 border border-[var(--mercury)] text-[var(--ghost)]">+</button><button onClick={() => removeFromCart(item.productId)} className="ml-auto font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-wider text-[var(--ghost)] transition hover:text-red-300">Remove</button></div></div></div></article>)}</div> : <div className="py-16 text-center"><ShoppingBag className="mx-auto text-[var(--ghost)]"/><p className="mt-4 font-[family-name:var(--font-mono)] text-sm text-[var(--ghost)]">Your cart is waiting.</p><Link href="/store" onClick={() => setOpen(false)} className="mt-5 inline-block text-xs uppercase tracking-[.14em] text-[var(--halo)]">Visit the store →</Link></div>}</div>
      <footer className="border-t border-[var(--mercury)] p-6"><div className="flex items-baseline justify-between"><span className="font-[family-name:var(--font-mono)] text-xs uppercase tracking-wider text-[var(--ghost)]">Subtotal</span><strong className="font-[family-name:var(--font-display)] text-2xl text-[var(--halo)]">{formatCurrency(subtotalCents)}</strong></div><CheckoutButton items={items} className="mt-5 w-full bg-[var(--halo)] px-5 py-4 font-[family-name:var(--font-display)] text-lg text-[var(--void)] disabled:cursor-not-allowed disabled:opacity-50">Checkout securely →</CheckoutButton>{items.length ? <button onClick={clearCart} className="mt-4 w-full font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-[.14em] text-[var(--ghost)] transition hover:text-[var(--bone)]">Clear cart</button> : null}</footer>
    </aside></> : null}
  </>
}
