import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { CalendarDays, Download, FileText, Mail, MapPin, Mic2, Music2, Phone, Shield, Users } from "lucide-react"
import { PressPhotoGallery } from "@/components/sandabado/press-photo-gallery"

export const metadata: Metadata = { title:"Press Kit — Sandābādo", description:"Official press kit for Sandābādo: bio, music, photos, technical details, and booking information.", openGraph:{ title:"Sandābādo — Official Press Kit", description:"Photos, bios, technical information, and booking contacts.", images:["/og.png"] } }

const sections = ["About", "Bios", "Band", "Music", "Coverage", "Video", "Photos", "Technical", "Stage plot", "Contact"]
const tracks = ["Rollin' Stone", "Lov3r", "M∆gic M∆n", "Soul of Gøld", "Pl3nty of TiⅯe", "Be∆st", "Jesus S∆ys", "∞ Love", "Lions D3n", "Evergold", "Think Say Do", "Great Mystery", "Par∆dise"]
const requirements = [["Stage", "Minimum 24' × 16' stage, warm amber wash, and a green room for the band."], ["Audio", "Full PA, four wedge monitors or IEMs, 90-minute soundcheck, and an experienced FOH engineer."], ["Backline", "Fender Twin or equivalent, Vox AC30 or equivalent, Ampeg SVT-class bass rig, keyboard DI, and a five-piece kit."], ["Hospitality", "Vegetarian options, bottled water, towels, nearby load-in parking, and green-room Wi-Fi."]]
const coverageTemplates = [
  { type:"Album review", outlet:"Publication name", headline:"A headline about ∞ LOVE will live here.", detail:"Add a verified pull quote, author, publication date, and destination URL when coverage is published." },
  { type:"Artist profile", outlet:"Publication name", headline:"A future profile of Sandābādo will live here.", detail:"Use this card for a long-form feature, interview, or local-scene story." },
  { type:"Live review", outlet:"Publication name", headline:"A future live review will live here.", detail:"Use this card for show coverage from Pioneertown, the desert circuit, or beyond." },
]

export default function PressPage() {
  return <div className="star-field min-h-screen">
    <header className="border-b border-[var(--gold)]/20 px-6 pb-16 pt-24 text-center sm:pb-20 sm:pt-32"><p className="text-[10px] uppercase tracking-[.3em] text-[var(--gold)]">Official press kit · 2026</p><h1 className="mt-4 font-[family-name:var(--font-display)] text-6xl tracking-[.08em] sm:text-8xl">SANDĀBĀDO</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-[var(--cream)]/70">Soul blues and desert rock from the high desert of California.</p><p className="mt-3 font-[family-name:var(--font-display)] text-2xl italic text-[var(--gold)]">∞ LOVE · September 26, 2026</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="mailto:press@sandabado.com?subject=Press%20kit%20request" className="inline-flex items-center gap-2 bg-[var(--gold)] px-5 py-3 text-xs font-semibold uppercase tracking-[.14em] text-[var(--obsidian)] transition hover:bg-[#e4c450]"><Download size={15}/>Request full press kit</a><Link href="/booking" className="inline-flex items-center gap-2 border border-white/35 px-5 py-3 text-xs font-semibold uppercase tracking-[.14em] text-[var(--cream)] transition hover:border-[var(--gold)] hover:text-[var(--gold)]"><Mail size={15}/>Booking inquiry</Link></div><dl className="mx-auto mt-14 grid max-w-3xl grid-cols-2 gap-px overflow-hidden border border-white/10 bg-white/10 sm:grid-cols-4"><Stat label="Tracks" value="13"/><Stat label="Genre" value="Soul blues / desert rock"/><Stat label="Label" value="Whole Body Records"/><Stat label="PRO" value="ASCAP"/></dl></header>
    <nav className="sticky top-16 z-40 overflow-x-auto border-b border-white/10 bg-[#0a0a0f]/85 px-6 py-3 backdrop-blur-md" aria-label="Press kit sections"><div className="mx-auto flex w-max min-w-full justify-center gap-5">{sections.map((section) => <a key={section} href={`#${slug(section)}`} className="whitespace-nowrap text-[10px] uppercase tracking-[.15em] text-[var(--cream)]/60 transition hover:text-[var(--gold)]">{section}</a>)}</div></nav>
    <main>
      <PressSection id="about" eyebrow="About" title="The hum never left."><div className="grid items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="relative mx-auto aspect-square w-full max-w-md overflow-hidden border border-[var(--gold)]/25"><Image src="/images/releases/sandabado-infinity-love.png" alt="∞ LOVE album artwork" fill sizes="(max-width: 1024px) 90vw, 35vw" className="object-cover"/></div><div className="space-y-5 text-base leading-7 text-[var(--cream)]/72"><p><strong className="font-medium text-[var(--cream)]">Sandābādo</strong> is the project of Jesse Gawlik, producer, multi-instrumentalist, and founder of Whole Body Records. Rooted in the Joshua Tree / Morongo Valley area, the project channels the raw energy of the high desert into soul blues and desert rock: primal, emotional, driving, and anthemic.</p><p>The debut record, <strong className="font-medium text-[var(--cream)]">∞ LOVE</strong>, is a thirteen-track journey recorded at Sandabado Studio. Written with Josh Tomaszewski and Christopher Kyser, it moves through devotion, transformation, independence, and the search for meaning.</p><p>Sandābādo is built independently: masters, publishing, and the artist-audience relationship remain with the artist and Whole Body Records.</p><blockquote className="border-l-2 border-[var(--gold)] pl-5 font-[family-name:var(--font-display)] text-2xl italic leading-9 text-[var(--gold)]/90">“Music as infrastructure. Frequency as medicine. The artist as architect.”</blockquote></div></div></PressSection>
      <PressSection id="bios" eyebrow="Bios" title="Artist bios"><div className="grid gap-5 lg:grid-cols-2"><Bio title="Short bio" label="~150 words"><p>Sandābādo is the solo project of Jesse Gawlik, a producer and musician based in Morongo Valley, California. The project pairs soul blues instrumentation with desert rock energy across the debut album, ∞ LOVE. Written with Josh Tomaszewski and Christopher Kyser, the thirteen-track record explores transformation, devotion, and the search for meaning. Released through Whole Body Records (ASCAP), the project is independently owned and made by humans in a room.</p><p className="mt-4">The live debut takes place at The Whole Body Gathering on September 26, 2026 at Red Dog Saloon in Pioneertown, California.</p></Bio><Bio title="Long bio" label="~350 words"><p>Jesse Gawlik followed a familiar music-industry path until it stopped feeling like his own. After early contact with major-label machinery, he stepped away to build a more independent practice: a studio, a label, a publishing relationship, and a direct connection to listeners.</p><p className="mt-4">Sandābādo is the result. Based in the Joshua Tree / Morongo Valley area, the project folds the voltage of desert rock into the grain and intimacy of soul blues. Its debut, ∞ LOVE, moves through thirteen archetypal songs—restlessness, devotion, resilience, confrontation, grace—written with Josh Tomaszewski and Christopher Kyser and recorded at Sandabado Studio.</p><p className="mt-4">The project’s live world is equally intentional: a room, a band, an audience, and a sound built to meet in real time. No AI was used in the music. All masters and publishing remain under Whole Body Records.</p></Bio></div></PressSection>
      <PressSection id="band" eyebrow="Band" title="The players"><div className="grid gap-5 md:grid-cols-3"><Player name="Jesse Gawlik" role="Vocals · Guitar · Production" body="Founder of Sandābādo and Whole Body Records. Producer, multi-instrumentalist, primary songwriter, and creative director."/><Player name="Josh Tomaszewski" role="Bass · Keys" body="Multi-instrumentalist and composer, providing the low-end foundation and melodic counterpoint."/><Player name="Christopher Kyser" role="Drums · Percussion" body="Drummer and composer, carrying the primal rhythmic backbone of the project’s desert-rock edge."/></div></PressSection>
      <PressSection id="music" eyebrow="Music" title="∞ LOVE"><div className="grid gap-7 lg:grid-cols-[.72fr_1.28fr]"><div><Image src="/images/releases/sandabado-infinity-love.png" alt="∞ LOVE album artwork" width={1000} height={1000} className="w-full border border-[var(--gold)]/25"/><dl className="mt-5 grid grid-cols-2 gap-x-6 gap-y-4 text-sm"><Detail label="Release" value="September 26, 2026"/><Detail label="Label" value="Whole Body Records"/><Detail label="Composers" value="Gawlik · Tomaszewski · Kyser"/><Detail label="Licensing" value="One-stop via Whole Body Records"/></dl></div><div className="border border-white/15 bg-black/25 p-5 sm:p-7"><p className="text-[10px] uppercase tracking-[.2em] text-[var(--gold)]">Track listing</p><ol className="mt-5 divide-y divide-white/10">{tracks.map((track,index) => <li key={track} className="flex gap-4 py-3"><span className="font-[family-name:var(--font-mono)] text-xs text-[var(--gold)]">{String(index + 1).padStart(2,"0")}</span><span className="text-sm text-[var(--cream)]/85">{track}</span></li>)}</ol></div></div><div className="mt-7 border border-white/15 bg-black/25 p-6 text-sm leading-6 text-[var(--cream)]/65"><strong className="font-medium text-[var(--cream)]">Sync & licensing:</strong> Masters and publishing are managed by Whole Body Records (ASCAP). For one-stop licensing, contact <a href="mailto:records@wholebody.earth" className="text-[var(--gold)] hover:underline">records@wholebody.earth</a>.</div></PressSection>
      <PressSection id="coverage" eyebrow="Press coverage" title="Stories, coming soon"><p className="mx-auto max-w-2xl text-center text-sm leading-6 text-[var(--cream)]/60">This section is ready for published reviews, interviews, and live coverage. The cards below are clearly marked layout samples and will be replaced with verified press links.</p><div className="mt-9 grid gap-5 md:grid-cols-3">{coverageTemplates.map((item) => <article key={item.type} className="border border-dashed border-[var(--gold)]/35 bg-black/20 p-6"><p className="text-[10px] uppercase tracking-[.18em] text-[var(--gold)]">Sample layout · {item.type}</p><div className="mt-6 flex h-11 w-32 items-center justify-center border border-white/15 text-[9px] uppercase tracking-[.16em] text-[var(--cream)]/40">Publication logo</div><p className="mt-4 text-xs uppercase tracking-[.14em] text-[var(--cream)]/45">{item.outlet}</p><h3 className="mt-3 font-[family-name:var(--font-display)] text-2xl leading-7">{item.headline}</h3><p className="mt-4 text-sm leading-6 text-[var(--cream)]/60">{item.detail}</p></article>)}</div></PressSection>
      <PressSection id="video" eyebrow="Video" title="Visuals"><div className="grid gap-7 md:grid-cols-[1.2fr_.8fr]"><Link href="/video" className="desert-glow flex aspect-video items-center justify-center border border-[var(--gold)]/25 text-center transition hover:border-[var(--gold)]"><div><Music2 className="mx-auto text-[var(--gold)]" size={30}/><p className="mt-4 text-xs uppercase tracking-[.18em] text-[var(--cream)]">View visual transmissions</p></div></Link><div className="flex flex-col justify-center"><p className="text-lg leading-8 text-[var(--cream)]/70">Album visualizer, studio footage, and performance material are available for editorial use on request.</p><a href="mailto:press@sandabado.com?subject=Video%20request" className="mt-6 inline-flex w-fit items-center gap-2 border border-[var(--gold)]/55 px-5 py-3 text-xs uppercase tracking-[.14em] text-[var(--gold)] transition hover:bg-[var(--gold)] hover:text-[var(--obsidian)]"><FileText size={15}/>Request video assets</a></div></div></PressSection>
      <PressSection id="photos" eyebrow="Photos" title="Press images"><p className="mx-auto mb-8 max-w-2xl text-center text-sm leading-6 text-[var(--cream)]/60">Select an image to view it larger. For high-resolution or additional press images, email the press team.</p><PressPhotoGallery/><div className="mt-7 text-center"><a href="mailto:press@sandabado.com?subject=High-resolution%20press%20images" className="inline-flex items-center gap-2 text-xs uppercase tracking-[.14em] text-[var(--gold)] hover:underline"><Download size={15}/>Request high-resolution photos</a></div></PressSection>
      <PressSection id="technical" eyebrow="Technical" title="Show requirements"><div className="grid gap-5 md:grid-cols-2">{requirements.map(([title,body]) => <article key={title} className="border border-white/15 bg-black/25 p-6"><Mic2 className="text-[var(--gold)]" size={22}/><h3 className="mt-4 font-[family-name:var(--font-display)] text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--cream)]/65">{body}</p></article>)}</div><div className="mt-8 text-center"><a href="mailto:booking@sandabado.com?subject=Technical%20rider%20request" className="inline-flex items-center gap-2 border border-[var(--gold)]/55 px-5 py-3 text-xs uppercase tracking-[.14em] text-[var(--gold)] transition hover:bg-[var(--gold)] hover:text-[var(--obsidian)]"><Download size={15}/>Request full technical rider</a></div></PressSection>
      <PressSection id="stage-plot" eyebrow="Stage plot" title="Stage layout"><div className="overflow-x-auto border border-white/15 bg-black/35 p-5 sm:p-8"><pre className="min-w-[38rem] font-[family-name:var(--font-mono)] text-xs leading-6 text-[var(--cream)]/70">{"AUDIENCE\n┌──────────────────────────────────────────────────────┐\n│ BASS / KEYS                  DRUMS      VOCALS / GUITAR │\n│ Ampeg SVT                    riser      Fender + Vox    │\n│ Josh Tomaszewski             Chris Kyser Jesse Gawlik   │\n│                                                      │\n│ Keys DI                      Lead vocal mic            │\n│                                                      │\n│ MON 1       MON 2            MON 3       MON 4        │\n└──────────────────────────────────────────────────────┘\n\nMinimum stage: 24' × 16' · Full input list and patch sheet available on contract."}</pre></div></PressSection>
      <PressSection id="contact" eyebrow="Contact" title="Contact"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Contact icon={Mail} label="Booking" href="mailto:booking@sandabado.com">booking@sandabado.com</Contact><Contact icon={Shield} label="Management" href="mailto:management@odin.agency">management@odin.agency</Contact><Contact icon={FileText} label="Press" href="mailto:press@sandabado.com">press@sandabado.com</Contact><Contact icon={Phone} label="Label" href="mailto:records@wholebody.earth">records@wholebody.earth</Contact></div><div className="mt-10 flex flex-wrap justify-center gap-x-6 gap-y-3 text-sm text-[var(--cream)]/55"><span className="inline-flex items-center gap-2"><MapPin size={15} className="text-[var(--gold)]"/>Joshua Tree / Morongo Valley, CA</span><span className="inline-flex items-center gap-2"><CalendarDays size={15} className="text-[var(--gold)]"/>The Whole Body Gathering · Sep 26, 2026</span><span className="inline-flex items-center gap-2"><Users size={15} className="text-[var(--gold)]"/>ODIN Management · Whole Body Records</span></div></PressSection>
    </main>
  </div>
}

function PressSection({ id, eyebrow, title, children }: { id:string; eyebrow:string; title:string; children:React.ReactNode }) { return <section id={id} className="scroll-mt-32 border-b border-white/10 px-6 py-16 sm:py-24"><div className="mx-auto max-w-6xl"><p className="text-center text-[10px] uppercase tracking-[.28em] text-[var(--gold)]">{eyebrow}</p><h2 className="mt-3 text-center font-[family-name:var(--font-display)] text-4xl sm:text-5xl">{title}</h2><div className="mt-11">{children}</div></div></section> }
function Stat({ label, value }: { label:string; value:string }) { return <div className="bg-[#0a0a0f]/80 px-4 py-5"><dt className="text-[10px] uppercase tracking-[.14em] text-[var(--cream)]/45">{label}</dt><dd className="mt-2 text-xs font-medium text-[var(--cream)]/90">{value}</dd></div> }
function Bio({ title, label, children }: { title:string; label:string; children:React.ReactNode }) { return <article className="border border-white/15 bg-black/25 p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><h3 className="font-[family-name:var(--font-display)] text-3xl">{title}</h3><span className="text-[10px] uppercase tracking-[.14em] text-[var(--gold)]">{label}</span></div><div className="mt-6 text-sm leading-7 text-[var(--cream)]/70">{children}</div></article> }
function Player({ name, role, body }: { name:string; role:string; body:string }) { return <article className="border border-white/15 bg-black/25 p-6 text-center"><Users className="mx-auto text-[var(--gold)]" size={26}/><h3 className="mt-5 font-[family-name:var(--font-display)] text-3xl">{name}</h3><p className="mt-2 text-[10px] uppercase tracking-[.18em] text-[var(--gold)]">{role}</p><p className="mt-5 text-sm leading-6 text-[var(--cream)]/65">{body}</p></article> }
function Detail({ label, value }: { label:string; value:string }) { return <div><dt className="text-[10px] uppercase tracking-[.14em] text-[var(--cream)]/45">{label}</dt><dd className="mt-1 text-sm text-[var(--cream)]/80">{value}</dd></div> }
function Contact({ icon:Icon, label, href, children }: { icon:typeof Mail; label:string; href:string; children:React.ReactNode }) { return <a href={href} className="border border-white/15 bg-black/25 p-5 text-center transition hover:border-[var(--gold)]/60"><Icon className="mx-auto text-[var(--gold)]" size={22}/><p className="mt-3 text-[10px] uppercase tracking-[.16em] text-[var(--gold)]">{label}</p><p className="mt-2 break-all text-sm text-[var(--cream)]/85">{children}</p></a> }
function slug(value:string) { return value.toLowerCase().replace(/\s+/g, "-") }
